from typing import List, Optional
from pydantic import BaseModel, Field



class ClientQuestionAnswer(BaseModel):
    question: str = Field(..., description="The vetting question asked to the client")
    answer: str = Field(..., description="The client's answer to the vetting question")

class MajorOption(BaseModel):
    major_id: str = Field(..., description="The unique database identifier of the major")
    name: str = Field(..., description="The display name of the major")

class CategoryOption(BaseModel):
    category_id: str = Field(..., description="The unique database identifier of the category")
    major_id: str = Field(..., description="The identifier of the major this category belongs to")
    name: str = Field(..., description="The display name of the category")

class SkillOption(BaseModel):
    skill_id: str = Field(..., description="The unique database identifier of the skill")
    name: str = Field(..., description="The display name of the skill")

class JobPostGenerationRequest(BaseModel):
    title: Optional[str] = Field(default=None, description="The client's suggested job title or project name")
    client_questions_and_answers: List[ClientQuestionAnswer] = Field(
        default=[],
        description="A list of vetting questions and the client's corresponding answers."
    )
    allowed_majors: List[MajorOption] = Field(
        ...,
        description="A list of allowed majors in the system database."
    )
    allowed_categories: List[CategoryOption] = Field(
        ...,
        description="A list of allowed categories in the system database."
    )
    available_skills: List[SkillOption] = Field(
        ...,
        description="A list of available system skills in the database."
    )

class JobPostGenerationResponse(BaseModel):
    title: str = Field(..., description="The generated/refined job title")
    major_id: str = Field(..., description="The ID of the chosen major from allowed_majors")
    category_id: str = Field(..., description="The ID of the chosen category from allowed_categories")
    system_skill_ids: List[str] = Field(..., description="A list of skill IDs selected from available_skills")
    custom_skills: List[str] = Field(..., description="A list of custom skill names generated by the AI")
    description: str = Field(..., description="Generated job description in markdown format")
    is_ai_generated: bool = Field(default=True, description="Indicates the description was AI-generated")
