from typing import List, Optional
from pydantic import BaseModel, Field



class MajorOption(BaseModel):
    major_id: str = Field(..., description="The unique database identifier of the major")
    name: str = Field(..., description="The display name of the major")

class CategoryOption(BaseModel):
    category_id: str = Field(..., description="The unique database identifier of the category")
    major_id: str = Field(..., description="The identifier of the major this category belongs to")
    name: str = Field(..., description="The display name of the category")

class SkillOption(BaseModel):
    skill_id: str = Field(..., description="The unique database identifier of the skill")
    name: str = Field(..., description="The display name of the skill")

class MilestoneGenerationResponse(BaseModel):
    title: str = Field(..., description="Tên milestone / Milestone title")
    amount: float = Field(..., description="Số tiền / Amount for the milestone")
    estimated_duration: str = Field(..., description="Thời lượng / Time frame (e.g. '2 tuần' or '2 weeks')")
    due_date: str = Field(..., description="Hạn hoàn thành / Milestone deadline in mm/dd/yyyy format")
    description: str = Field(..., description="Mô tả công việc và kết quả mong đợi / Detailed summary of scope")
    deliverables: str = Field(..., description="Sản phẩm bàn giao / Deliverables list")
    acceptance_criteria: str = Field(..., description="Tiêu chí nghiệm thu / Acceptance criteria")

class JobPostGenerationRequest(BaseModel):
    client_prompt: str = Field(
        ...,
        description="The user's prompt or requirements for the job post."
    )

class JobPostDetailsGenerationResponse(BaseModel):
    title: str = Field(..., description="The generated/refined job title. MUST be written in English.")
    major_id: str = Field(..., description="The ID of the chosen major from allowed_majors")
    category_id: str = Field(..., description="The ID of the chosen category from allowed_categories")
    system_skill_ids: List[str] = Field(..., description="A list of skill IDs selected from available_skills")
    custom_skills: List[str] = Field(..., description="A list of custom skill names generated by the AI. MUST be written in English.")
    description: str = Field(..., description="Generated job description in plain text format. MUST be in Vietnamese if client_prompt is in Vietnamese, and MUST be in English if client_prompt is in English.")
    budget_min: Optional[float] = Field(None, description="The minimum budget estimated for the job in GC (GigCoins).")
    budget_max: Optional[float] = Field(None, description="The maximum budget estimated for the job in GC (GigCoins).")
    estimated_duration: Optional[str] = Field(None, description="The estimated duration of the job, e.g. '2 weeks', '1 month', '3 months'.")
    is_ai_generated: bool = Field(default=True, description="Indicates the description was AI-generated")

class JobPostHiringPlanGenerationRequest(BaseModel):
    client_prompt: str = Field(..., description="The original user prompt or requirement")
    title: str = Field(..., description="The approved job title")
    description: str = Field(..., description="The approved job description")
    budget_min: Optional[float] = Field(None, description="The approved minimum budget")
    budget_max: Optional[float] = Field(None, description="The approved maximum budget")
    estimated_duration: Optional[str] = Field(None, description="The approved estimated duration/timeline")
    proposal_closing_date: str = Field(..., description="The proposal closing date / deadline in YYYY-MM-DD or MM/DD/YYYY format")

class JobPostHiringPlanGenerationResponse(BaseModel):
    question_recruitment: List[str] = Field(
        default=[],
        description="A list of generated recruitment/vetting questions based on the prompt. MUST be in Vietnamese if client_prompt is in Vietnamese, and MUST be in English if client_prompt is in English."
    )
    milestones: List[MilestoneGenerationResponse] = Field(
        default=[],
        description="A list of proposed milestones for the job post. MUST follow the prompt language."
    )
