from typing import List, Optional
from pydantic import BaseModel, Field



class MajorOption(BaseModel):
    major_id: str = Field(..., description="The unique database identifier of the major")
    name: str = Field(..., description="The display name of the major")

class CategoryOption(BaseModel):
    category_id: str = Field(..., description="The unique database identifier of the category")
    major_id: str = Field(..., description="The identifier of the major this category belongs to")
    name: str = Field(..., description="The display name of the category")

class SkillOption(BaseModel):
    skill_id: str = Field(..., description="The unique database identifier of the skill")
    name: str = Field(..., description="The display name of the skill")

class JobPostGenerationRequest(BaseModel):
    client_prompt: str = Field(
        ...,
        description="The user's prompt or requirements for the job post."
    )

class JobPostGenerationResponse(BaseModel):
    title: str = Field(..., description="The generated/refined job title. MUST be written in English.")
    major_id: str = Field(..., description="The ID of the chosen major from allowed_majors")
    category_id: str = Field(..., description="The ID of the chosen category from allowed_categories")
    system_skill_ids: List[str] = Field(..., description="A list of skill IDs selected from available_skills")
    custom_skills: List[str] = Field(..., description="A list of custom skill names generated by the AI. MUST be written in English.")
    description: str = Field(..., description="Generated job description in markdown format. MUST be in Vietnamese if client_prompt is in Vietnamese, and MUST be in English if client_prompt is in English.")
    is_ai_generated: bool = Field(default=True, description="Indicates the description was AI-generated")
    question_recruitment: List[str] = Field(
        default=[],
        description="A list of generated recruitment/vetting questions based on the prompt. MUST be in Vietnamese if client_prompt is in Vietnamese, and MUST be in English if client_prompt is in English."
    )
